name: builder

on:
  workflow_dispatch:
  push:

jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: lepalom/ros-deb-builder-action@main
        with:
          DEB_DISTRO: bullseye
          ROS_DISTRO: debian
          ROSDEP_SOURCE: yaml file:///home/runner/work/ros-one-packages/ros-one-packages/rosdep.yaml debian
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          SBUILD_CONF: "$extra_repositories = [ 'deb [trusted=yes] http://debrob.upc.edu/debian-robotics bullseye-robotics main', 'deb http://deb.debian.org/debian bullseye-backports main']; $build_dep_resolver = 'aptitude';  $manual_depends = ['cmake (>= 3.22.1-1)'];"
          
          
